### ISSUE TITLE
Streams not appearing in 2.6.2

### ISSUE THREAD

**Issue by LeviSnoot** [Banderi/PicartoNotifier#3]
Hi! Long time user of this excellent extension. Just wanted to let you know as I saw you had just made an update that the new version isn't displaying any streams. 

![image](https://github.com/user-attachments/assets/88102ca2-6737-4f9d-9248-1f0399e08322)

If there's a way for me to provide logs I'm happy to do so. Not seeing anything in the console for the extension window.

**Comment by Banderi** [comment]
Yeahh been battling with the update since yesterday.
Try ~~2.6.3~~ 2.6.4!

**Comment by LeviSnoot** [comment]
Works great now, thanks!
